CREATE DATABASE DesafioRoman_Manha;
GO

USE DesafioRoman_Manha;
GO

CREATE TABLE USUARIO (
	IdUsuario SMALLINT PRIMARY KEY IDENTITY,
	IdTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPOUSUARIO(IdtipoUsuario),
	NomeUsuario VARCHAR(30) NOT NULL,
	EmailUsuario VARCHAR(40) NOT NULL UNIQUE,
	SenhaUsuario VARCHAR(25) NOT NULL,
);
GO

SELECT * FROM USUARIO;

CREATE TABLE TIPOUSUARIO (
	IdTipoUsuario SMALLINT PRIMARY KEY IDENTITY,
	TipoUsuario VARCHAR (25) NOT NULL UNIQUE
);
GO

SELECT * FROM TIPOUSUARIO;

CREATE TABLE TEMA (
	IdTema SMALLINT PRIMARY KEY IDENTITY,
	NomeTema VARCHAR (30) NOT NULL
);
GO

SELECT * FROM TEMA;

CREATE TABLE PROJETO(
	IdProjeto SMALLINT PRIMARY KEY IDENTITY,
	IdTema SMALLINT FOREIGN KEY REFERENCES TEMA(IdTema),
	NomeProjeto VARCHAR (50) NOT NULL UNIQUE,
	DescricaoProjeto VARCHAR (500) NOT NULL
);
GO

SELECT * FROM PROJETO;
